//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.11 at 08:27:13 AM SAST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://org.chibamu.takeaways/OrderService/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package orgg.chibamu.takeaways.order.domain;
